### ISSUE TITLE
Blink BugFix?

### ISSUE THREAD

**Issue by DerSeb90** [chaostreff-flensburg/ruetueta-loet-badge#2]
Hallo,
ich habe im Stream gesehen das es Probleme mit dem blinken gab. Und es wurde gesagt der fix ist ein anderer Wiederstand? Habe es leider nur halb mitbekommen. Könnt ihr mir unerfahrenen bitte helfen?

**Comment by adb-sh** [comment]
Hey :) Im vorhinein hatten wir nicht mit frischen Batterien getestet. Daher kann es sein, dass durch das Überbrücken von R6 kurzzeitig ein zu hoher Strom durch den Transistor Q4 geflossen ist und diesen gekillt hat. Dadurch stockt die Schaltung und die beiden linken Ü-Punkte leuchten gar nicht. Du solltest im Set noch einen weiteren Transistor finden; erstezte den Defekten einfach mit diesem. Starte deine Platine, indem du R6 dann kurzzeitig mit den übrigen 120 Ohm Wiederstand überbrückst. Dann sollte auch deine Platine laufen :D

**Comment by DerSeb90** [comment]
Hi,
also nochmal zur Sicherheit. Ich löte alles wie im repo beschrieben und Brücke nicht mit einem Draht sondern mit dem 120 Ohm Wiederstand falls es nicht blinkt?

**Comment by adb-sh** [comment]
Genau. Wenn du ganz sicher gehen willst, dass nichts kaputt geht, kannst du es zunächst mit einem größeren Wiederstand versuchen. (z.B. 4,7kOhm). Ich messe das heute Abend nochmal genau durch, dann hast du eine verlässlichere Antwort.

**Comment by adb-sh** [comment]
120 Ohm sind groß genug
